services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./deploy/api/api.development.Dockerfile     # Change as needed
    ports:
      - "8000:8000"
    environment:                                              # Change as needed
      - k1=v1
    depends_on:
      - db
    volumes:
      - ./apps/api/app:/app

  web:
    build:
      context: .
      dockerfile: ./deploy/web/web.development.Dockerfile     # Change as needed
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development                                  # Change as needed
    depends_on:
      - api
    volumes:
      - ./apps/web/app:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: